# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.

# Basic Site Settings
locale                   : "en-US"
site_theme               : "default" # The available themes options are "default", "air", "sunrise", "mint", "dirt" and "contrast"
title                    : "Yifan Li"
title_separator          : "-"
name                     : &name "Yifan Li"
description              : &description "Yifan Li's academic portfolio"   # Update this with a general description of your site, this is the default if not overridden by a page
url                      : https://eavanli.github.io # The base hostname & protocol for your site e.g. "https://[your GitHub username].github.io",
                                                           # or if you already have some other page hosted on Github then use "https://[your GitHub username].github.io/[Your Repo Name]"
baseurl                  : "/liyifan" # the subpath of your site, e.g. "/blog"
repository               : "eavanli/liyifan/"

# Site Author - The following control what appear as part of the author content on the side bar.
#               If a field is blank the icon and link will not appear, otherwise it will be shown.
#               Additional customization can be done by editing /_includes/author-profile.html
author:
  # Biographic information
  avatar           : "https://eavanli.github.io/liyifan/images/liyifan.JPG"
  name             : "李艺帆"
  bio              : "讲师"
  location         : "北京，中国"
  employer         : "首都经济贸易大学人工智能学院"
  uri              : # URL
  email            : "liyifan@cueb.edu.cn" 

# 强制指定主页
defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true
  - scope:
      path: "_pages/index.md"
    values:
      permalink: /

  
